version: 0.2

# phases:
#   build:
#     commands:
#       - echo "Practicing CodeBuild"
#       - echo "Example for CodeBuild - buildspec file"
#       - node --version
#       - npm --version

# phases:
#   install:
#     commands:
#       - echo "Example for INSTALL phase"

#   pre_build:
#     commands:
#       - echo "Example for PRE_BUILD phase"

#   build:
#     commands:
#       - echo "Example for BUILD phase"

#   post_build:
#     commands:
#       - echo "Example for POST_BUILD phase"

phases:
  build:
    commands:
      - echo "Command 1"
      - echo "Command 2"
      - echo "Command 3"
      - echo "Command 4"